### ISSUE TITLE
Cannot read property 'toFixed' of null

### ISSUE THREAD

**Issue by dentuzhik** [Wei-Xia/alfred-stock-price-workflow#1]
Hey, just downloaded your workflow from releases page, and immediately got the following errors:
```
Starting debug for 'Stock'

[2018-07-25 12:00:51][ERROR: input.scriptfilter] Code 1: {
	"items": [
		{
			"title": "TypeError: Cannot read property 'toFixed' of null\n    at alfy.fetch.then.result (/Users/dentuzhik/Documents/Alfred.alfredpreferences/workflows/user.workflow.02423D22-42A3-49BB-B933-2829C60AEC0D/index.js:7:72)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nTypeError: Cannot read property 'toFixed' of null\n    at alfy.fetch.then.result (/Users/dentuzhik/Documents/Alfred.alfredpreferences/workflows/user.workflow.02423D22-42A3-49BB-B933-2829C60AEC0D/index.js:7:72)\n    at <anonymous>\n```\n\n-\nStock undefined\nAlfred 3.6.2\ndarwin x64 17.7.0",
				"largetype": "TypeError: Cannot read property 'toFixed' of null\n    at alfy.fetch.then.result (/Users/dentuzhik/Documents/Alfred.alfredpreferences/workflows/user.workflow.02423D22-42A3-49BB-B933-2829C60AEC0D/index.js:7:72)\n    at <anonymous>"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
[2018-07-25 12:00:52][ERROR: input.scriptfilter] Code 1: {
	"items": [
		{
			"title": "TypeError: Cannot read property 'toFixed' of null\n    at alfy.fetch.then.result (/Users/dentuzhik/Documents/Alfred.alfredpreferences/workflows/user.workflow.02423D22-42A3-49BB-B933-2829C60AEC0D/index.js:7:72)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nTypeError: Cannot read property 'toFixed' of null\n    at alfy.fetch.then.result (/Users/dentuzhik/Documents/Alfred.alfredpreferences/workflows/user.workflow.02423D22-42A3-49BB-B933-2829C60AEC0D/index.js:7:72)\n    at <anonymous>\n```\n\n-\nStock undefined\nAlfred 3.6.2\ndarwin x64 17.7.0",
				"largetype": "TypeError: Cannot read property 'toFixed' of null\n    at alfy.fetch.then.result (/Users/dentuzhik/Documents/Alfred.alfredpreferences/workflows/user.workflow.02423D22-42A3-49BB-B933-2829C60AEC0D/index.js:7:72)\n    at <anonymous>"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
```

Do I need to configure some API keys? I haven't been able to find anything in configuration.

**Comment by Wei-Xia** [comment]
@dentuzhik  it's API's issue. Please use it during trading hour. None trading hour sometimes causes this issue.

**Comment by dentuzhik** [comment]
Ok, thank you!

**Comment by dentuzhik** [comment]
Will you accept a PR though with a nicer error handling?

**Comment by Wei-Xia** [comment]
@dentuzhik Sure, you are very welcome to contribute PR! Appreciate it!
