### ISSUE TITLE
Getting parse error when looking up stock price

### ISSUE THREAD

**Issue by chrismessina** [Wei-Xia/alfred-stock-price-workflow#3]
![CleanShot 2020-09-06 at 11 54 02](https://user-images.githubusercontent.com/22610/92333098-aa584300-f037-11ea-80d1-950c2f1d7ef6.png)

Perhaps [this API](https://api.iextrading.com/1.0/stock/tsla/batch?types=quote) has been shut down?

```
[12:01:08.697] Stock[Script Filter] Script with argv 'tsla' finished
[12:01:08.704] ERROR: Stock[Script Filter] Code 1: {
	"items": [
		{
			"title": "ParseError: Unexpected token F in JSON at position 0 in \"https://api.iextrading.com/1.0/stock/tsla/batch?types=quote\": \nForbidden...\n    at /Users/messina/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.76E26C54-7B01-4307-86BD-C02C7C17B9F0/node_modules/got/index.js:118:14\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nParseError: Unexpected token F in JSON at position 0 in \"https://api.iextrading.com/1.0/stock/tsla/batch?types=quote\": \nForbidden...\n    at /Users/messina/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.76E26C54-7B01-4307-86BD-C02C7C17B9F0/node_modules/got/index.js:118:14\n```\n\n-\nStock undefined\nAlfred 4.1.1\ndarwin x64 19.6.0",
				"largetype": "ParseError: Unexpected token F in JSON at position 0 in \"https://api.iextrading.com/1.0/stock/tsla/batch?types=quote\": \nForbidden...\n    at /Users/messina/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.76E26C54-7B01-4307-86BD-C02C7C17B9F0/node_modules/got/index.js:118:14"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
```

**Comment by Wei-Xia** [comment]
@chrismessina  yeah...the stock API is down for a long while, don't have a chance to find a good and free stock price API to replace.

**Comment by chrismessina** [comment]
Have you considered IEX? https://iexcloud.io/docs/api/#book

**Comment by Wei-Xia** [comment]
@chrismessina  seems like this iexcloud free account has 5k/month request limit, but I will give a try.

**Comment by chrismessina** [comment]
I think it would be reasonable for people to register w/ IEXCloud to get their own key so they can use it without hitting your limits.

**Comment by Wei-Xia** [comment]
@chrismessina  good call.....If i can't find a good & free stock price API, I'll take this approach

**Comment by Wei-Xia** [comment]
@chrismessina thanks for the suggestion....pushed the latest change, this workflow finally works now.
